[project]
name = "vsort"
version = "0.1.0"
description = "Fast and lightweight script that sorts your files by type."
authors = [
    { name="vxid-dev" }
]
requires-python = ">=3.10"

[project.scripts]
vsort = "vsort.main:main"

